version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true  
    environment:
      PORT: 5000
      MONGO_URI: mongodb://db_container:27017/
      DB_NAME: main_db
    depends_on:
      - mongo_db


volumes:
  mongo_db: {}
